// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkwulSKQXnURCRq5URY7cTGIF-1Ofhqp8',
    appId: '1:924775096997:web:c0374cf1dcb4765d18a34c',
    messagingSenderId: '924775096997',
    projectId: 'cravory-food-delivery-app',
    authDomain: 'cravory-food-delivery-app.firebaseapp.com',
    storageBucket: 'cravory-food-delivery-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA32ruLovXnS9kqPrE8YvAA0QIJ0LYAYWU',
    appId: '1:924775096997:android:84ae2d7655ab1b9f18a34c',
    messagingSenderId: '924775096997',
    projectId: 'cravory-food-delivery-app',
    storageBucket: 'cravory-food-delivery-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBB71RUy9ODqe-d5C95VcJmZgcHwM9xgJU',
    appId: '1:924775096997:ios:084b1ed48ccb450618a34c',
    messagingSenderId: '924775096997',
    projectId: 'cravory-food-delivery-app',
    storageBucket: 'cravory-food-delivery-app.firebasestorage.app',
    iosBundleId: 'com.example.cravory',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBB71RUy9ODqe-d5C95VcJmZgcHwM9xgJU',
    appId: '1:924775096997:ios:084b1ed48ccb450618a34c',
    messagingSenderId: '924775096997',
    projectId: 'cravory-food-delivery-app',
    storageBucket: 'cravory-food-delivery-app.firebasestorage.app',
    iosBundleId: 'com.example.cravory',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkwulSKQXnURCRq5URY7cTGIF-1Ofhqp8',
    appId: '1:924775096997:web:f729b4ba5983dc4c18a34c',
    messagingSenderId: '924775096997',
    projectId: 'cravory-food-delivery-app',
    authDomain: 'cravory-food-delivery-app.firebaseapp.com',
    storageBucket: 'cravory-food-delivery-app.firebasestorage.app',
  );

}